### ISSUE TITLE
`aws ecr get-login` has been deprecated

### ISSUE THREAD

**Issue by harrywang** [testdrivenio/flask-react-aws#30]
In this section: https://testdriven.io/courses/aws-flask-react/elastic-container-registry/

You have:
`$ aws ecr get-login --region us-west-1 --no-include-email`

`aws ecr get-login` is deprecated:

https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login-password.html

The following command should be used instead:

```
  aws ecr get-login-password \
    --region us-west-1 \
| docker login \
    --username AWS \
    --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.us-west-1.amazonaws.com
```

**Comment by harrywang** [comment]
accordingly, in `buildspec.yml` file:
`- $(aws ecr get-login --no-include-email --region $AWS_REGION)`

can also be replaced by:

`- aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com`

**Comment by mjhea0** [comment]
updated! thanks.
